import React from "react";
import { Table, Thead, Tbody, Tr, Th, Td } from "@chakra-ui/react";

const Schedule = () => {
  const FebNum = 30;
  const MarNum = 20;

  return (
    <>
      <Table w="100%" mb="5">
        <Tbody>
          <Tr>
            <Th>2/1</Th>
            <Th>2/2</Th>
            <Th>2/3</Th>
            <Th>2/4</Th>
            <Th>2/5</Th>
            <Th>2/6</Th>
            <Th>2/7</Th>
            <Th>2/8</Th>
            <Th>2/9</Th>
            <Th>2/10</Th>
          </Tr>
          <Tr>
            <Td></Td>
            <Td></Td>
            <Td></Td>
            <Td></Td>
            <Td></Td>
            <Td></Td>
            <Td></Td>
            <Td></Td>
            <Td></Td>
          </Tr>
          <Tr>
            <Th>2/11</Th>
            <Th>2/12</Th>
            <Th>2/13</Th>
            <Th>2/14</Th>
            <Th>2/15</Th>
            <Th>2/16</Th>
            <Th>2/17</Th>
            <Th>2/18</Th>
            <Th>2/19</Th>
            <Th>2/20</Th>
          </Tr>
          <Tr>
            <Td></Td>
            <Td></Td>
            <Td></Td>
            <Td></Td>
            <Td></Td>
            <Td></Td>
            <Td></Td>
            <Td></Td>
            <Td></Td>
          </Tr>
          <Tr>
            <Th>2/21</Th>
            <Th>2/22</Th>
            <Th>2/23</Th>
            <Th>2/24</Th>
            <Th>2/25</Th>
            <Th>2/26</Th>
            <Th>2/27</Th>
            <Th>2/28</Th>
          </Tr>
          <Tr>
            <Td></Td>
            <Td></Td>
            <Td></Td>
            <Td></Td>
            <Td></Td>
            <Td></Td>
            <Td></Td>
            <Td></Td>
            <Td></Td>
          </Tr>
        </Tbody>
      </Table>
      <Table w="100%">
        <Tbody>
          <Tr>
            <Th>3/1</Th>
            <Th>3/2</Th>
            <Th>3/3</Th>
            <Th>3/4</Th>
            <Th>3/5</Th>
            <Th>3/6</Th>
            <Th>3/7</Th>
            <Th>3/8</Th>
            <Th>3/9</Th>
            <Th>3/10</Th>
          </Tr>
          <Tr>
            <Td></Td>
            <Td></Td>
            <Td></Td>
            <Td></Td>
            <Td></Td>
            <Td></Td>
            <Td></Td>
            <Td></Td>
            <Td></Td>
          </Tr>
          <Tr>
            <Th>3/11</Th>
            <Th>3/12</Th>
            <Th>3/13</Th>
            <Th>3/14</Th>
            <Th>3/15</Th>
            <Th>3/16</Th>
            <Th>3/17</Th>
            <Th>3/18</Th>
            <Th>3/19</Th>
            <Th>3/20</Th>
          </Tr>
          <Tr>
            <Td></Td>
            <Td></Td>
            <Td></Td>
            <Td></Td>
            <Td></Td>
            <Td></Td>
            <Td></Td>
            <Td></Td>
            <Td></Td>
          </Tr>
          <Tr>
            <Th>3/21</Th>
            <Th>3/22</Th>
            <Th>3/23</Th>
            <Th>3/24</Th>
            <Th>3/25</Th>
            <Th>3/26</Th>
            <Th>3/27</Th>
            <Th>3/28</Th>
            <Th>3/29</Th>
            <Th>3/30</Th>
          </Tr>
          <Tr>
            <Td></Td>
            <Td></Td>
            <Td></Td>
            <Td></Td>
            <Td></Td>
            <Td></Td>
            <Td></Td>
            <Td></Td>
            <Td></Td>
          </Tr>
        </Tbody>
      </Table>
    </>
  );
};

export default Schedule;
